name: Document Conversion

on:
  push:
    branches: 
      - master
    paths: 
      - docs/requirements/*
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    name: Generate Requirements Doc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: cd "docs/requirements"
      - uses: docker://pandoc/latex:2.9
        with:
          args: "*.md -o output/requirements.pdf"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
